### ISSUE TITLE
Uncaught TypeError: window.require is not a function

### ISSUE THREAD

**Issue by mjiang108** [open-source-labs/Chronos#62]
I just cloned the repo, rolled back to Node 12.18.3, and ran `npm rebuild`. But when I run `npm start` I get the mentioned error in the browser console. When I run `npm electron` I get a blank screen. [Stackoverflow](https://stackoverflow.com/questions/56265958/electronjs-window-require-not-a-function) says to set `nodeIntegration: true` in Main.ts, which it already is. Also tried [making a preload.js file](https://github.com/electron/electron/issues/9920#issuecomment-336757899), which didn't quite work. I've never used Electron before, so please forgive my ignorance, but is there a way around this?

<img width="1792" alt="Screen Shot 2021-01-05 at 11 31 02 PM (2)" src="https://user-images.githubusercontent.com/9983876/103745290-0e722000-4fb4-11eb-95af-9b53518b96a7.png">

**Comment by mjiang108** [comment]
Figure it out. I had to run `npm run both` which opens up Electron, rather than `npm start`

**Comment by sanket1726** [comment]
Didn't get your solution @mjiang108
